Repository sonia-auv/interface_rs485, pull requests merged in 2022-05, with the labels that each got.

#17 add schedule actions
  .github/workflows/docker-image-perception-develop.yml
  .github/workflows/docker-image-perception-feature.yml
  .github/workflows/docker-image-perception-fix.yml
  package.xml
Labels: Priority: High, Type: Feature

#18 Feature/simulation
  .github/pull_request_template.md
  .github/workflows/docker-image-perception-master.yml
  Dockerfile
  launch/interface_rs485.launch
  launch/interface_rs485_sim.launch
  src/interface_rs485_sim.py
Labels: Priority: Medium, Type: Feature

#21 fixed branch'
  README.md
  launch/interface_rs485.launch
  launch/interface_rs485_sim.launch
  src/interface_rs485_sim.py
Labels: Priority: High, Type: Bug
